on:
  push:
    branches:
      - dev

jobs:
  gerar_imagem_job:
    runs-on: ubuntu-latest
    name: Construindo uma imaegme e enviando ao DockerHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
              
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
        
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=volverinejr/usuarios-ms:v${{ github.run_number }}
          cache-to: type=inline
          tags: volverinejr/usuarios-ms:v${{ github.run_number }}
